name: Windows 10 - LiteManager (ArifKembiri)

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://github.com/arifkembiri/Windows10-LiteManager/raw/refs/heads/main/Download.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
